version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@3.0.0
  aws-cli: circleci/aws-cli@0.1.9
  aws_assume_role: lbh-hackit/aws_assume_role@0.1.0

executors:
  docker-python:
    docker:
      - image: circleci/python:3.7
  docker-terraform:
    docker:
      - image: "hashicorp/terraform:1.1.9"
  docker-dotnet:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:6.0

references:
  workspace_root: &workspace_root "~"
  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

commands:
  assume-role-and-persist-workspace:
    description: "Assumes deployment role and persists credentials across jobs"
    parameters:
      aws-account:
        type: string
    steps:
      - checkout
      - aws_assume_role/assume_role:
          account: <<parameters.aws-account>>
          profile_name: default
          role: "LBH_Circle_CI_Deployment_Role"
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - .aws
  terraform-init-then-plan:
    description: "Initializes and run plan from terraform configuration"
    parameters:
      environment:
        type: string
    steps:
      - *attach_workspace
      - checkout
      - run:
          command: |
            cd ./terraform/<<parameters.environment>>/
            terraform get -update=true
            terraform init
          name: get and init
      - run:
          name: plan
          command: |
            cd ./terraform/<<parameters.environment>>/
            terraform plan -out=plan.out
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - .aws
            - project/*
  terraform-compliance:
    description: "Run Terraform Compliance checks"
    parameters:
      environment:
        type: string
    steps:
      - *attach_workspace
      - checkout
      - run:
          command: |
            cd ./terraform/<<parameters.environment>>/
            apk add --update --no-cache python3 && ln -sf python3 /usr/bin/python
            apk add --update --no-cache g++ gcc libxslt-dev python3-dev
            python3 -m ensurepip
            pip3 install --no-cache --upgrade pip setuptools
            pip install terraform-compliance
            terraform-compliance -f terraform-compliance/ -p plan.out
          name: terraform compliance
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - .aws
  terraform-apply:
    description: "Runs Terraform Apply"
    parameters:
      environment:
        type: string
    steps:
      - *attach_workspace
      - checkout
      - run:
          name: apply
          command: |
            cd ./terraform/<<parameters.environment>>/
            terraform apply -auto-approve plan.out
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - .aws
  deploy-lambda:
    description: "Deploys API via Serverless"
    parameters:
      stage:
        type: string
    steps:
      - *attach_workspace
      - checkout
      - setup_remote_docker
      - run:
          name: Install Node.js
          command: |
            curl -sL https://deb.nodesource.com/setup_18.x | bash -
            apt-get update && apt-get install -y nodejs
      - run:
          name: Install serverless CLI
          command: npm i -g serverless
      - run:
          name: Build lambda
          command: |
            cd ./TenureInformationApi/
            chmod +x ./build.sh
            ./build.sh
      - run:
          name: Deploy lambda
          command: |
            cd ./TenureInformationApi/
            npm i serverless-associate-waf
            npm i @serverless/safeguards-plugin --save-dev
            sls deploy --stage <<parameters.stage>> --conceal
jobs:
  check-code-formatting:
    executor: docker-dotnet
    steps:
      - checkout
      - run:
          name: Install dotnet format
          command: dotnet tool install dotnet-format --tool-path ./dotnet-format-local/
      - run:
          name: Run formatter check
          command: ./dotnet-format-local/dotnet-format --check
  build-and-test:
    executor: docker-python
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: build
          command: docker-compose build tenure-information-api-test
      - run:
          name: Run tests
          command: docker-compose run tenure-information-api-test
  assume-role-development:
    executor: docker-python
    steps:
      - assume-role-and-persist-workspace:
          aws-account: $AWS_ACCOUNT_DEVELOPMENT
  assume-role-staging:
    executor: docker-python
    steps:
      - assume-role-and-persist-workspace:
          aws-account: $AWS_ACCOUNT_STAGING
  assume-role-production:
    executor: docker-python
    steps:
      - assume-role-and-persist-workspace:
          aws-account: $AWS_ACCOUNT_PRODUCTION
  terraform-init-and-plan-development:
    executor: docker-terraform
    steps:
      - terraform-init-then-plan:
          environment: "development"
  terraform-compliance-development:
    executor: docker-terraform
    steps:
      - terraform-compliance:
          environment: "development"
  terraform-apply-development:
    executor: docker-terraform
    steps:
      - terraform-apply:
          environment: "development"
  terraform-init-and-plan-staging:
    executor: docker-terraform
    steps:
      - terraform-init-then-plan:
          environment: "staging"
  terraform-compliance-staging:
    executor: docker-terraform
    steps:
      - terraform-compliance:
          environment: "staging"
  terraform-apply-staging:
    executor: docker-terraform
    steps:
      - terraform-apply:
          environment: "staging"
  terraform-init-and-plan-production:
    executor: docker-terraform
    steps:
      - terraform-init-then-plan:
          environment: "production"
  terraform-compliance-production:
    executor: docker-terraform
    steps:
      - terraform-compliance:
          environment: "production"
  terraform-apply-production:
    executor: docker-terraform
    steps:
      - terraform-apply:
          environment: "production"
  deploy-to-development:
    executor: docker-dotnet
    steps:
      - deploy-lambda:
          stage: "development"
  deploy-to-staging:
    executor: docker-dotnet
    steps:
      - deploy-lambda:
          stage: "staging"
  deploy-to-production:
    executor: docker-dotnet
    steps:
      - deploy-lambda:
          stage: "production"

workflows:
  check-and-deploy-development:
    jobs:
      - build-and-test:
          context:
            - api-nuget-token-context
            - SonarCloud
